name: Triggered Action

on:
  repository_dispatch:
    types: [reminder_triggered]

jobs:
  send_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Extract Information from Payload
        id: extract
        run: |
          echo "Title: ${{ github.event.client_payload.title }}"
          echo "URL: ${{ github.event.client_payload.url }}"
          title="${{ github.event.client_payload.title }}"
          url="${{ github.event.client_payload.url }}"
          
          # Store title and URL for further use
          echo "::set-output name=title::$title"
          echo "::set-output name=url::$url"

      - name: Send Pushover Notification
        run: |
          curl -s \
            --form-string "token=${{ secrets.PUSHOVER_APP_TOKEN }}" \
            --form-string "user=${{ secrets.PUSHOVER_USER_KEY }}" \
            --form-string "message=Tab Reminder Triggered!%0ATitle: ${{ steps.extract.outputs.title }}%0AURL: ${{ steps.extract.outputs.url }}" \
            https://api.pushover.net/1/messages.json


