name: Triggered Action

on:
  repository_dispatch:
    types: [reminder_triggered]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Send Pushover Notification
        run: |
          curl -s \
            --form-string "token=${{ secrets.PUSHOVER_APP_TOKEN }}" \
            --form-string "user=${{ secrets.PUSHOVER_USER_KEY }}" \
            --form-string "message=GitHub Action Triggered!" \
            https://api.pushover.net/1/messages.json

